services:
  dataset-app: &server
    build: .
    restart: always
    ports:
      - "8000:8000"
    environment:
      - UVICORN_HOST=0.0.0.0
      - UVICORN_PORT=8000
      - API_ROOT=/
      - WORKER_ENDPOINT=http://dataset-worker:8000
    volumes:
      - /opt/app:/var/lib/app
  dataset-worker:
    <<: *server
    ports: []
    command:
      - /app/.venv/bin/uvicorn
      - main:worker
